language: ruby

rvm:
  - ruby-1.9.2
  - ruby-1.9.3
  - ruby-2.0
  - ruby-2.1
  - ruby-2.2
  - ruby-head
  - jruby-19mode
  - jruby-1.6.8
  - jruby-1.7.18
  - jruby-head
  - rbx-19mode
  - rbx-2
  - rbx-head

os:
  - linux
  - osx

jdk:
  - openjdk7

matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
