language: ruby
sudo: false
rvm:
- ruby-1.9.2
- ruby-1.9.3
- ruby-2.0
- ruby-2.1
- ruby-2.2
- jruby-19mode
- jruby-1.7.22
- jruby-9.0.0.0
- rbx-19mode
- rbx-2
os:
- linux
- osx
matrix:
  allow_failures:
  - rvm: jruby-9.0.0.0
  exclude:
  - os: osx
    rvm: ruby-1.9.2
  - os: osx
    rvm: ruby-2.2
  - os: osx
    rvm: jruby-19mode
  - os: osx
    rvm: jruby-1.7.22
  - os: osx
    rvm: jruby-9.0.0.0
  - os: osx
    rvm: rbx-19mode
  - os: osx
    rvm: rbx-2
