#@ load("@ytt:template", "template")

#@ load("ruby.star", "cruby_versions")
#@ all_cruby_versions = []
#@ all_cruby_versions.extend(cruby_versions["supported"])
#@ all_cruby_versions.extend(cruby_versions["beta"])

#@ load("ruby.star", "jruby_versions")
#@ all_jruby_versions = []
#@ all_jruby_versions.extend(jruby_versions["supported"])
#@ all_jruby_versions.extend(jruby_versions["beta"])

#@ load("ruby.star", "truffleruby_versions")
#@ all_truffleruby_versions = []
#@ all_truffleruby_versions.extend(truffleruby_versions["supported"])
#@ all_truffleruby_versions.extend(truffleruby_versions["beta"])

---
#@ def registry_image(image_repo, image_tag):
platform: linux
image_resource:
  type: registry-image
  source:
    repository: #@ image_repo
    tag: #@ image_tag
#@ end

---
#@ def task_inputs():
- name: ci
- name: nokogiri-pr
  path: nokogiri
#@ end

---
#@ def pend_pr(pr_resource_name, context=None):
put: #@ pr_resource_name
params:
  path: #@ pr_resource_name
#!  base_context: ci.nokogiri.org
  status: PENDING
  #@ if/end context:
  context: #@ context
#@ end

---
#@ def put_to_pr_on_everything(pr_resource_name, context=None):
on_failure:
  put: #@ pr_resource_name
  params:
    path: #@ pr_resource_name
#!    base_context: ci.nokogiri.org
    status: FAILURE
    #@ if/end context:
    context: #@ context
on_error:
  put: #@ pr_resource_name
  params:
    path: #@ pr_resource_name
#!    base_context: ci.nokogiri.org
    status: ERROR
    #@ if/end context:
    context: #@ context
on_abort:
  put: #@ pr_resource_name
  params:
    path: #@ pr_resource_name
#!    base_context: ci.nokogiri.org
    status: ERROR
    #@ if/end context:
    context: #@ context
#!on_success:
#!  put: #@ pr_resource_name
#!  params:
#!    path: #@ pr_resource_name
#!    base_context: ci.nokogiri.org
#!    status: SUCCESS
#!    #@ if/end context:
#!    context: #@ context
#@ end

---
% require "common_prelude.rb"

resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource


resources:
  - name: ci
    type: git
    icon: cog
    source:
      uri: https://github.com/sparklemotion/nokogiri/
      branch: master
      disable_ci_skip: true #! always get the latest pipeline configuration
  - name: nokogiri-pr
    type: pull-request
    icon: github
    check_every: 15m
    webhook_token: ((nokogiri-pr-webhook-token))
    source:
      repository: sparklemotion/nokogiri
      access_token: ((github-repo-status-access-token))
      ignore_paths:
        - "*.md"
        - "concourse/"
        - "suppressions/"
        - ".github/"
        - "Vagrantfile"


jobs:
  - name: pr-pending
    public: true
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
      - #@ pend_pr("nokogiri-pr")


  - name: cruby-on-vanilla-ubuntu
    public: true
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: ["pr-pending"]
      - task: rubocop
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "bionic"))
          inputs: #@ task_inputs()
          run:
            path: ci/concourse/tasks/rake-test/rubocop.sh
      - task: rake-test
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "bionic"))
          inputs: #@ task_inputs()
          params:
            TEST_WITH_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh


#@ for ruby_version in all_cruby_versions:
  - name: #@ "cruby-{}".format(ruby_version)
    public: true
    #@ if/end ruby_version in cruby_versions["supported"]:
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: ["cruby-on-vanilla-ubuntu"]
      - task: rake-test-system-libraries
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-{}".format(ruby_version)))
          inputs: #@ task_inputs()
          params:
            TEST_WITH_SYSTEM_LIBRARIES: t
            #@ if/end ruby_version == cruby_versions["supported"][-1]:
            CC_TEST_REPORTER_ID: ((code_climate_reporter_id_nokogiri))
          run:
            path: ci/concourse/tasks/rake-test/run.sh
      - task: rake-test-vendored-libraries
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-{}".format(ruby_version)))
          inputs: #@ task_inputs()
          run:
            path: ci/concourse/tasks/rake-test/run.sh
      - task: rake-test-valgrind
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-{}".format(ruby_version)))
          inputs: #@ task_inputs()
          params:
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
#@ end

#@ for ruby_version in all_jruby_versions:
  - name: #@ "jruby-{}".format(ruby_version)
    public: true
    #@ if/end ruby_version in jruby_versions["supported"]:
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: ["cruby-on-vanilla-ubuntu"]
      - task: rake-test
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "jruby-{}".format(ruby_version)))
          inputs: #@ task_inputs()
          run:
            path: ci/concourse/tasks/rake-test/run.sh
#@ end

#@ for ruby_version in all_truffleruby_versions:
  - name: #@ "truffle-{}".format(ruby_version)
    public: true
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: ["cruby-on-vanilla-ubuntu"]
      - task: rake-test
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "truffle-{}".format(ruby_version)))
          inputs: #@ task_inputs()
          run:
            path: ci/concourse/tasks/rake-test/run.sh
#@ end

  - name: cruby-on-musl
    public: true
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        passed: #@ ["cruby-{}".format(ruby_version) for ruby_version in cruby_versions["supported"]]
      - task: rake-test-system-libraries
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "alpine"))
          inputs: #@ task_inputs()
          params:
            TEST_WITH_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
      - task: rake-test-valgrind
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "alpine"))
          inputs: #@ task_inputs()
          params:
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh


  - name: cruby-with-libxmlruby
    public: true
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: #@ ["cruby-{}".format(ruby_version) for ruby_version in cruby_versions["supported"]]
      - task: rake-test-system-libraries
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-{}".format(cruby_versions["supported"][-1])))
          inputs: #@ task_inputs()
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
            TEST_WITH_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
      - task: rake-test-valgrind
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-{}".format(cruby_versions["supported"][-1])))
          inputs: #@ task_inputs()
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh


  - name: cruby-gem-test
    public: true
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: #@ ["cruby-{}".format(ruby_version) for ruby_version in cruby_versions["supported"]]
      - task: build
        config:
          "_": #@ template.replace(registry_image("larskanis/rake-compiler-dock-mri-x86_64-linux", "<%= RakeCompilerDock::IMAGE_VERSION %>"))
          inputs: #@ task_inputs()
          outputs:
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-build.sh
      - in_parallel:
        - task: install-and-test
          config:
            "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-{}".format(cruby_versions["supported"][-1])))
            inputs:
              - #@ template.replace(task_inputs())
              - name: gems
            run:
              path: ci/concourse/tasks/gem-test/gem-install-and-test.sh
        - task: install-and-test-on-musl
          config:
            "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "alpine"))
            inputs:
              - #@ template.replace(task_inputs())
              - name: gems
            run:
              path: ci/concourse/tasks/gem-test/gem-install-and-test.sh


  - name: cruby-native-gem-test
    public: true
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: #@ ["cruby-{}".format(ruby_version) for ruby_version in cruby_versions["supported"]]
      - task: build
        config:
          "_": #@ template.replace(registry_image("larskanis/rake-compiler-dock-mri-x86_64-linux", "<%= RakeCompilerDock::IMAGE_VERSION %>"))
          inputs: #@ task_inputs()
          outputs:
            - name: gems
          params:
            BUILD_NATIVE_GEM: t
          run:
            path: ci/concourse/tasks/gem-test/gem-build.sh
      - in_parallel:
        <% $native_ruby_versions.each do |ruby_version| %>
        - task: install-and-test-<%= ruby_version %>
          config:
            "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "mri-<%= ruby_version %>"))
            inputs:
              - #@ template.replace(task_inputs())
              - name: gems
            run:
              path: ci/concourse/tasks/gem-test/gem-install-and-test.sh
        <% end %>
        - task: install-and-test-on-musl
          config:
            "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "alpine"))
            inputs:
              - #@ template.replace(task_inputs())
              - name: gems
            run:
              path: ci/concourse/tasks/gem-test/gem-install-and-test.sh


  - name: jruby-gem-test
    public: true
    _: #@ template.replace(put_to_pr_on_everything("nokogiri-pr"))
    plan:
      - get: ci
      - get: nokogiri-pr
        trigger: true
        version: every
        passed: #@ ["jruby-{}".format(ruby_version) for ruby_version in jruby_versions["supported"]]
      - task: build
        config:
          "_": #@ template.replace(registry_image("larskanis/rake-compiler-dock-jruby", "<%= RakeCompilerDock::IMAGE_VERSION %>"))
          inputs: #@ task_inputs()
          outputs:
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-build-java.sh
      - task: install-and-test
        config:
          "_": #@ template.replace(registry_image("flavorjones/nokogiri-test", "jruby-{}".format(jruby_versions["supported"][-1])))
          inputs:
            - #@ template.replace(task_inputs())
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-install-and-test.sh


  - name: pr-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: nokogiri-pr
        trigger: true
        version: every
        passed:
          - cruby-on-musl
          - cruby-with-libxmlruby
          - cruby-gem-test
          - cruby-native-gem-test
          - jruby-gem-test
      - put: nokogiri-pr
        params: { path: nokogiri-pr, status: SUCCESS }
